### ISSUE TITLE
Create components at runtime

### ISSUE THREAD

**Issue by FlaPS** [nippur72/PolymerTS#31] opened 2015-07-21 18:27 UTC
Hello.
Visual Studio 2013/ typescript 1.5

* I just create object at runtime this way:
<code>  var el:any = document.createElement('login-form');</code>
<code> document.appendChild(el);     </code>
is there ay way use strictly typed objects like this ?  
<code>var el:LoginForm = new LoginForm();</code>
<code>document.body.appendChild(el); //	Argument of type 'LoginForm' is not assignable to parameter of type 'Node'.</code>

* I don't wont put any line of java script in html templates, and manage all the code with types in TS
How I can access the Class instance associated with dom-element like:
<code>var el:any = document.createElement('login-form');</code>
<code>el['login-form.ts-Scope?'].dataProvider = data;</code>
<code>el['login-form.ts-Scope?'].addEventListener("loginTriggered", myHandler);</code>
* Also is there any possible issues with initialization of "model" in case of property set?

Great thanks for this repo!

**Comment by nippur72** [comment] 2015-07-22 06:58
Hi,

1) the wrong type is a temporary issue, we are waiting for this issue
<https://github.com/Microsoft/TypeScript/issues/574> to be solved in
TypeScript. When it will be fixed, your "el" will be an extension of type
`HTMLElement` and you will be able to do DOM operations with it.

In the while, just use cast operators. Please note that the correct way is:

var el = LoginForm.create(); // not new LoginForm()
document.body.appendChild(el);

that is, use the "create" method to create instances of the element, as
normal "new" isn't enough.

2)

// the two are equivalent
var el = document.createElement('login-form');
var el = LoginForm.create();

your "el" is both of type "LoginForm" and "HTMLElement", the problem is
that it doesn't have a type annotation stick to it.

Use cast operator:

var el:LoginForm = <any> LoginForm.create();

// ... once your element is attached to DOM and initialized ...

el.myproperty = "hello";  // works because el is of type "LoginForm"

(<HTMLElement>el).addEventListener("loginTriggered", myHandler); // cast el
to HTMLElement

3) Can you please specify what do you mean with

*Also is there any possible issues with initialization of "model" in case
of property set?*


Unfortunately Polymer doesn't allow property getters and setters, so for
now they are not supported.


2015-07-21 20:27 GMT+02:00 FlaPS <notifications@github.com>:

**Closed** 2015-08-06 08:26 UTC
Labels: question
