### ISSUE TITLE
polymer-ts typings errors

### ISSUE THREAD

**Issue by jcimoch** [nippur72/PolymerTS#73] opened 2016-03-15 17:07 UTC
Hi, I have following configuration 
tsc version is 1.8.7

tsconfig

``` js
{
  "compilerOptions": {
    "module": "system",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "out": "."
  },
  "exclude": [
    "node_modules",
    "app/bower_components"
  ],
  "filesGlob": [
    "typings/browser.d.ts"
  ],
  "files": [
    "app/elements/my-element/my-element.ts",
    "typings/browser.d.ts"
  ]
}

```

typings.json

``` js
{
  "version": false,
  "dependencies": {},
  "ambientDependencies": {
    "polymer": "registry:dt/polymer#1.1.6+20160123034809",
    "polymer-ts": "registry:dt/polymer-ts#0.1.19+20151211074327"
  }
}

```

and I'm trying to compile one of yours element example. I got those erros 

``` shell
typings/browser/ambient/polymer-ts/index.d.ts(103,11): error TS2415: Class 'Base' incorrectly extends base class 'PolymerBase'.
  Property '$' is optional in type 'Base' but required in type 'PolymerBase'.
typings/browser/ambient/polymer-ts/index.d.ts(106,9): error TS2300: Duplicate identifier 'is'.
typings/browser/ambient/polymer/index.d.ts(23,13): error TS2430: Interface 'Base' incorrectly extends interface 'PolymerBase'.
typings/browser/ambient/polymer/index.d.ts(78,5): error TS2300: Duplicate identifier 'is'.
typings/browser/ambient/polymer/index.d.ts(151,5): error TS2425: Class 'PolymerBase' defines instance member property '$$', but extended class 'Base' defines it as instance member function.
typings/browser/ambient/polymer/index.d.ts(311,37): error TS2503: Cannot find namespace 'webcomponents'.
typings/browser/ambient/polymer/index.d.ts(313,42): error TS2503: Cannot find namespace 'webcomponents'.
typings/browser/ambient/polymer/index.d.ts(317,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Polymer' must be of type '{ (prototype: Element): FunctionConstructor; Class(prototype: Element): Function; dom: dom; appen...', but here has type 'PolymerStatic'.
error TS5033: Could not write file '.': EISDIR: illegal operation on a directory, open '.'

```

Is there something that I'm doing wrong?

**Comment by nippur72** [comment] 2016-03-15 18:09
I'm not sure, can you please try using the `polymer.d.ts` directly from the `bower_components` directory?

**Comment by kito99** [comment] 2016-03-25 19:56
I'm having the same issue with this tsd.json file (just created it today), so these are recent commits:

```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "mocha/mocha.d.ts": {
      "commit": "a44529fcb1e1cdc0355e71c42a6048de99b57c34"
    },
    "chai/chai.d.ts": {
      "commit": "a44529fcb1e1cdc0355e71c42a6048de99b57c34"
    },
    "assertion-error/assertion-error.d.ts": {
      "commit": "a44529fcb1e1cdc0355e71c42a6048de99b57c34"
    },
    "polymer/polymer.d.ts": {
      "commit": "a44529fcb1e1cdc0355e71c42a6048de99b57c34"
    },
    "webcomponents.js/webcomponents.js.d.ts": {
      "commit": "a44529fcb1e1cdc0355e71c42a6048de99b57c34"
    }
  }
}
```

**Comment by kito99** [comment] 2016-03-25 19:57
@nippur72 , which bower_components directory?

**Comment by nippur72** [comment] 2016-03-26 09:47
@kito99 
```
/// <reference path="bower_components/polymer-ts/polymer-ts.d.ts" />
```
if you still have problems, please setup an example repo that I can clone, so I can look into it.

**Comment by kito99** [comment] 2016-03-26 15:46
Thanks. To be clear, that is what I'm using.  This only happens when
including the polymer.d.ts type definition. There appears to be an
incompatibility between the latest polymer-ts and polymer type definitions.

**Comment by nippur72** [comment] 2016-03-27 08:48
@kito99 yes there's a mismatch, that's why I was against publishing it on `DefinitelyTyped`.

In the future, once we convert the package to npm, no typings will be necessary as typescript is able to read them directly from the `node_modules` directory, thanks to the `typings` property in `package.json`.

**Comment by kito99** [comment] 2016-03-27 13:50
Hmmm..will that fix the problem, though? Will we be able to use
polymer.d.ts with Polymer-TS? Seems like a pretty logical thing to do :-).

**Comment by nippur72** [comment] 2016-03-27 14:19
In theory it should be possible to use the typings without using `reference` or `tsd` but the PolymerTS package needs to be turned into a true module. The side effect is that users will have to switch to `npm` instead of `bower`.

Since I don't want to force a specific pattern, I'm waiting for typescript 2.0 which should support publishing both in module and global (see [this](https://github.com/Microsoft/TypeScript/issues/7125)).

**Comment by jcimoch** [comment] 2016-04-04 10:04
Is there a temporary solution if I want to use both of them at the same time without getting compilation error?

**Comment by nippur72** [comment] 2016-04-04 11:51
I've pulled an update for `polymer-ts.d.ts`to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8837

(it needs to be merged before you can use it).

**Comment by kito99** [comment] 2016-04-07 20:08
So you're saying if we pull this version, it'll work properly with PolymerTS?

**Comment by jcimoch** [comment] 2016-04-08 08:45
Still having issues after update 
```js
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer-ts/index.d.ts(110,11): error TS2415: Class 'Base' incorrectly extends base class 'PolymerBase'.
  Property '$' is optional in type 'Base' but required in type 'PolymerBase'.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer-ts/index.d.ts(113,9): error TS2300: Duplicate identifier 'is'.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer/index.d.ts(23,13): error TS2430: Interface 'Base' incorrectly extends interface 'PolymerBase'.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer/index.d.ts(78,5): error TS2300: Duplicate identifier 'is'.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer/index.d.ts(151,5): error TS2425: Class 'PolymerBase' defines instance member property '$$', but extended class 'Base' defines it as instance member function.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer/index.d.ts(311,37): error TS2503: Cannot find namespace 'webcomponents'.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer/index.d.ts(313,42): error TS2503: Cannot find namespace 'webcomponents'.
/Users/Jarek/Desktop/Praca/webRtcTests/client/typings/browser/ambient/polymer/index.d.ts(317,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Polymer' must be of type '{ (prototype: Element): FunctionConstructor; Class(prototype: Element): Function; dom: dom; appen...', but here has type 'PolymerStatic'.
```

**Comment by Draccoz** [comment] 2016-07-11 14:00
Can PolymerTS extend Polymer typings? Or can there be a flag or anything to not include Polymer typings by PolymerTS? I do understand you don't want to force any specific pattern, but at this moment you are forcing people to either not use PolymerTS typings or to not use Polymer typings ^^. Would be cool to be able to use both.

**Comment by nippur72** [comment] 2016-07-11 14:46
@Draccoz yes I think it makes more sense to have PolymerTS extend from Polymer (from DefinitelyTyped). I'm only waiting for TS2.0 to be out (it's a matter of days now) since there are a lot of changes regarding how typings are handled.

**Comment by Draccoz** [comment] 2016-07-11 14:49
Ok, if it's a matter of days it's cool = ). Can't wait for this to happen :D.

**Comment by nippur72** [comment] 2016-07-13 09:57
I'm trying to make the above change (PolymerTS that extends DefinitelyTyped/Polymer.d.ts) but there is name clashing between the names `polymer` and `Polymer` because they are used in both projects. 

I don't know how to solve this as it would result in a breaking change. Perhaps we can have `PolymerTS` published as npm module so that one can import it without being force to a specific name, e.g.:
```ts
import { Base } from "polymer-ts";

class MyEl extends Base { 
}
MyEl.register();
```
what do you think? I'm open to suggestions :)

**Comment by Draccoz** [comment] 2016-07-13 10:19
What if you use namespace instead of module? Namespaces use to merge nicely as long as the exported properties do not overlap.
As for making PolymerTS into an importable module, that would break compatibility with the previous versions. As far as I'm concerned (correct me if I'm wrong), typings might yell if something is declared globally + module way. Always worth a try though.
Anyway, I'll take a look into it when I get back home today and am very eager to help with it :).
Meanwhile, you could have a look at what I've been playing with: https://github.com/Draccoz/typed-polymer
It's my fan project, maybe you will find anything interesting in it.

**Comment by nippur72** [comment] 2016-07-13 10:35
@Draccoz the two projects already use `namespace` (formerly called internal modules), the problem is that names do overlap. Perhaps I could manage to reduce overlapping but the result would be quite messy.

As for making it an external module, with TS2.0, we can have both worlds thanks to UMD module definitions and the new `export as namespace ...`. 

For example we could have a `polymer-ts.d.ts` like this:
```ts
export class Base ...
export as namespace Polymer;
```
- used as a module you can `import { Base }`;
- used as a script (no `import` or `export`) you can access it via the global published variable `Polymer` (e.g. `Polymer.Base`).

**Comment by Draccoz** [comment] 2016-07-13 10:40
Oh that is nice! So TS2 brings more to the table than I thought it would. Oh I will definitely give it a shot :smile: .

**Comment by Draccoz** [comment] 2016-07-26 11:10
After few days of hacking, I give up. There is no way (that I could find) to redefine a polymer.Base class to be extended with `register()` class. I'd suggest using different namespace or class name, but that's a breaking change.
Anybody had more luck?

**Comment by kito99** [comment] 2017-11-16 21:35
Generally speaking using other typings isn't going to work out well. This will hopefully be ironed otu with Polymer 2's generated typings.

**Closed by kito99** 2017-11-16 21:35 UTC
Labels: wontfix
